# It's slightly tempting to automate testing of TCC reload working, sandbox not
# faulting, doing a matrix across the two features...
# 
# The starting point, though, is validating that the autotools pain was at all
# worth it. Does the base library build? Good.
#
# The optional features might flow down from Arch/Gentoo's nice build
# environments in the future.
language: c
compiler: gcc

matrix:
  allow_failures:
    - os: osx
    - dist: precise
  include:
    - os: linux
      env: "NOTE='Ubuntu Trusty: secondary target, basic features'"
      dist: trusty
      sudo: false # going to try the fancy Beta stuff
      addons:
        apt:
          packages: # tcc/seccomp don't seem to be in the whitelist, oh well!
            - libncursesw5-dev
      script:
        - echo "travis_fold:start:bootstrap_and_configure"
        - ./bootstrap 
        - ./configure 
        - echo "travis_fold:end:bootstrap_and_configure"
        - make
        - "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/lib"
        - "PATH=$PATH:$(pwd)/bin"
        - "make DESTDIR=$(pwd) install"
        - echo "travis_fold:start:smoke_test_cannot_look"
        - time timeout 1 blindsight `which blindsight` || true
        - echo "travis_fold:end:smoke_test_cannot_look"
    - os: linux
      env: "NOTE='Arch Linux: main target platform, all bells and whistles'"
      sudo: required
      services: docker
      before_install:
        - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
      script: 
        - echo "travis_fold:end:makepkg"
    - os: linux
      env: "NOTE='Ubuntu Precise: old automake incapable of clean builds'"
      dist: precise 
      sudo: required
      before_install:
        - sudo apt-get update -qq # automake... I'm dependant on at least 1.13? Yuck.
        - automake --version      # AC_CONFIG_MACRO_DIRS is showstopper, probably others too.
        - sudo apt-get install -qq libncursesw5-dev libseccomp-dev libtcc-dev tcc
      script:
        - echo "travis_fold:start:bootstrap_and_configure"
        - ./bootstrap && ./configure
        - echo "travis_fold:end:bootstrap_and_configure"
        - make
        - sudo make install
        - echo "travis_fold:start:smoke_test_cannot_look"
        - time timeout 1 blindsight `which blindsight` || true
        - echo "travis_fold:end:smoke_test_cannot_look"
    - os: osx
      env: "NOTE='OSX + Homebrew: never manually tested, but might work!'"
      before_install:
        - brew update  # fixes some dependency check for ruby 2.x, sorry :(
      install:
        - echo "travis_fold:start:brew_setup"
        - mkdir Formula && git mv pkg/homebrew/blindsight.rb Formula/
        - git -c user.name='t' -c user.email='t@t.com' commit -m 't'
        - mkdir -p `brew --repo`/Library/Taps/travis
        - ln -s `pwd` `brew --repo`/Library/Taps/travis/homebrew-btest
        - brew tap --repair
        - echo "travis_fold:end:brew_setup"
      script:
        - brew install --HEAD blindsight
        - echo "travis_fold:start:smoke_test_cannot_look"
        - "brew test blindsight"
        - "brew audit --strict blindsight || true"
        - "brew info blindsight"
        - echo "travis_fold:end:smoke_test_cannot_look"

# parsed by arch-travis.sh, not travis-ci:
arch:
  packages:
    - autoconf  # build-time
    - tcc
    - ncurses
    - libseccomp  # optional
  script:
    - echo "travis_fold:start:makepkg"
    - "(cd pkg/archlinux && makepkg -i --noconfirm)"
    - echo "travis_fold:start:smoke_test_cannot_look"
    - time timeout 1 blindsight `which blindsight` || true  # TODO check $? 124
    - echo "travis_fold:end:smoke_test_cannot_look"

